export const STATE = {
	STATE_UNINITIALIZED_UNSPECIFIED: "STATE_UNINITIALIZED_UNSPECIFIED",
	STATE_INIT: "STATE_INIT",
	STATE_TRYOPEN: "STATE_TRYOPEN",
	STATE_OPEN: "STATE_OPEN",
	STATE_CLOSED: "STATE_CLOSED",
};

export const STATUS_COLOR = {
	[STATE.STATE_OPEN]: "#37cc6e",
	[STATE.STATE_CLOSED]: "#ff2745",
	[STATE.STATE_INIT || STATE.STATE_TRYOPEN || STATE.STATE_UNINITIALIZED_UNSPECIFIED]: "#ffb323",
};
