export default Object.freeze([
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },
    {
        height: '',
        result: '',
        tx_hash: '',
        messages: [],
        fee: "",
        timestamp: "",
    },

]);
